module.exports = {
    // ...
    transform: {
      // ...
      '.+\\.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$': 'jest-transform-stub',
      '^.+\\.svg$': '<rootDir>/svgTransform.js'
    },
    // ...
  }